[tool.coverage.run]
source = ["openwisp_network_topology"]
parallel = true
concurrency = ["multiprocessing"]
omit = [
    "openwisp_network_topology/__init__.py",
    "*/tests/*",
    "*/migrations/*",
]

[tool.docstrfmt]
extend_exclude = ["**/*.py"]

[tool.isort]
known_third_party = ["django", "django_x509"]
known_first_party = ["openwisp_users", "openwisp_utils", "openwisp_network_topology", "openwisp_controller", "openwisp_monitoring"]
default_section = "THIRDPARTY"
line_length = 88
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
force_grid_wrap = 0
