#!/bin/bash
set -e

coverage run runtests.py --tag=no_parallel
coverage run runtests.py --parallel --exclude-tag=no_parallel
WIFI_MESH=1 coverage run runtests.py --parallel \
  --exclude-tag=no_parallel \
  --exclude-tag=selenium_tests
SAMPLE_APP=1 coverage run ./runtests.py --parallel \
  --exclude-tag=no_parallel \
  --exclude-tag=selenium_tests
coverage combine
coverage xml
