# Generated by Django 2.2.14 on 2020-07-15 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.TOPOLOGY_NODE_MODEL),
        migrations.swappable_dependency(settings.CONFIG_DEVICE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceNode',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.CONFIG_DEVICE_MODEL,
                    ),
                ),
                (
                    'node',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.TOPOLOGY_NODE_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
                'swappable': 'TOPOLOGY_DEVICE_DEVICENODE_MODEL',
                'unique_together': {('node', 'device')},
            },
        ),
    ]
