# Generated by Django 3.0.7 on 2020-06-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sample_network_topology", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="properties",
            field=models.TextField(
                blank=True,
                default=dict,
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="addresses",
            field=models.TextField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name="node",
            name="properties",
            field=models.TextField(
                blank=True,
                default=dict,
            ),
        ),
    ]
