# Generated by Django 3.0.9 on 2020-09-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sample_network_topology", "0002_json_properties")]

    operations = [
        migrations.AddField(
            model_name="link",
            name="user_properties",
            field=models.TextField(
                blank=True,
                default=dict,
                help_text="If you need to add additional data to this link use this field",
                verbose_name="user defined properties",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="user_properties",
            field=models.TextField(
                blank=True,
                default=dict,
                help_text="If you need to add additional data to this node use this field",
                verbose_name="user defined properties",
            ),
        ),
    ]
