# Generated by Django 3.0.7 on 2020-06-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("topology", "0009_remove_old_addresses")]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="properties",
            field=models.TextField(
                blank=True,
                default=dict,
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="addresses",
            field=models.TextField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="node",
            name="properties",
            field=models.TextField(
                blank=True,
                default=dict,
            ),
        ),
    ]
