# Generated by Django 3.0.9 on 2020-09-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("topology", "0012_update_openvpn_netjson_ids")]

    operations = [
        migrations.AddField(
            model_name="link",
            name="user_properties",
            field=models.TextField(
                blank=True,
                default=dict,
                help_text="If you need to add additional data to this link use this field",
                verbose_name="user defined properties",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="user_properties",
            field=models.TextField(
                blank=True,
                default=dict,
                help_text="If you need to add additional data to this node use this field",
                verbose_name="user defined properties",
            ),
        ),
    ]
