SIMPLE_MESH_DATA = {
    '64:70:02:c3:03:b2': [
        {
            'mac': '64:70:02:c3:03:b3',
            'mtu': 1500,
            'multicast': True,
            'name': 'mesh0',
            'txqueuelen': 1000,
            'type': 'wireless',
            'up': True,
            'wireless': {
                'channel': 11,
                'clients': [
                    {
                        'auth': True,
                        'authorized': True,
                        'ht': True,
                        'mac': 'a4:bc:3f:ae:c7:0c',
                        'mfp': False,
                        'noise': -90,
                        'signal': -52,
                        'vendor': 'TP-LINK TECHNOLOGIES CO.,LTD.',
                        'vht': False,
                        'wmm': True,
                    },
                    {
                        'auth': True,
                        'authorized': True,
                        'ht': True,
                        'mac': '2a:9a:fb:12:11:77',
                        'mfp': False,
                        'noise': -94,
                        'signal': -58,
                        'vendor': 'TP-LINK TECHNOLOGIES CO.,LTD.',
                        'vht': False,
                        'wmm': True,
                    },
                ],
                'country': 'ES',
                'frequency': 2462,
                'htmode': 'HT20',
                'mode': '802.11s',
                'noise': -95,
                'signal': -61,
                'ssid': 'Test Mesh',
                'tx_power': 17,
            },
        }
    ],
    'a4:bc:3f:ae:c7:0b': [
        {
            'mac': 'a4:bc:3f:ae:c7:0c',
            'mtu': 1500,
            'multicast': True,
            'name': 'mesh0',
            'txqueuelen': 1000,
            'type': 'wireless',
            'up': True,
            'wireless': {
                'channel': 11,
                'clients': [
                    {
                        'auth': True,
                        'authorized': True,
                        'ht': True,
                        'mac': '64:70:02:C3:03:B3',
                        'mfp': False,
                        'noise': -98,
                        'signal': -64,
                        'vendor': 'TP-LINK TECHNOLOGIES CO.,LTD.',
                        'vht': False,
                        'wmm': True,
                    },
                    {
                        'auth': True,
                        'authorized': True,
                        'ht': True,
                        'mac': '2a:9a:fb:12:11:77',
                        'mfp': False,
                        'noise': -96,
                        'signal': -60,
                        'vendor': 'TP-LINK TECHNOLOGIES CO.,LTD.',
                        'vht': False,
                        'wmm': True,
                    },
                ],
                'country': 'ES',
                'frequency': 2462,
                'htmode': 'HT20',
                'mode': '802.11s',
                'noise': -95,
                'signal': -56,
                'ssid': 'Test Mesh',
                'tx_power': 17,
            },
        }
    ],
    '2a:9a:fb:12:11:76': [
        {
            'mac': '2a:9a:fb:12:11:77',
            'mtu': 1500,
            'multicast': True,
            'name': 'mesh0',
            'txqueuelen': 1000,
            'type': 'wireless',
            'up': True,
            'wireless': {
                'channel': 11,
                'clients': [
                    {
                        # Link properties
                        'auth': True,
                        'authorized': True,
                        'noise': -92,
                        'signal': -56,
                        # Node properties
                        'ht': True,
                        'mfp': False,
                        'vht': False,
                        'wmm': True,
                        'mac': 'a4:bc:3f:ae:c7:0c',
                        'vendor': 'TP-LINK TECHNOLOGIES CO.,LTD.',
                    },
                ],
                'country': 'ES',
                'frequency': 2462,
                'htmode': 'HT20',
                'mode': '802.11s',
                'noise': -95,
                'signal': -64,
                'ssid': 'Test Mesh',
                'tx_power': 17,
            },
        }
    ],
}
